# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_userinfo_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pubtime',
        ),
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
